# baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = '箪食'
theme = "hugo-theme-stack"
defaultcontentlanguage = "zh-cn"

# paginate = 20

hasCJKLanguage = true
# disqusShortname = "yourdiscussshortname"

[params]
    description = "一箪食，一瓢饮。"
    mainSections = ["post"]
    
[params.footer]
    since = 2023

[params.sidebar]
    compact = true
    subtitle = "一箪食，一瓢饮。"

[params.sidebar.avatar]
    enabled = false

# [[params.widgets.homepage]]
#     type = "search"

[[params.widgets.homepage]]
    type = "archives"

    [params.widgets.homepage.params]
        limit = 5

[[params.widgets.homepage]]
    type = "tag-cloud"

    [params.widgets.homepage.params]
        limit = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[[params.widgets.page]]
    type = "toc"

[params.article]
    math = true
    readingTime = false

# Markdown renderer configuration
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

# [module]
# [[module.imports]]
# path = "github.com/CaiJimmy/hugo-theme-stack/v3"
